#!/usr/bin/python
# vim: set fileencoding=latin-1
#
#  Problem 45
#
# Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
#   Triangle      Tn=n(n+1)/2       1, 3, 6, 10, 15, ...
#   Pentagonal      Pn=n(3n−1)/2      1, 5, 12, 22, 35, ...
#   Hexagonal       Hn=n(2n−1)      1, 6, 15, 28, 45, ...
#
# It can be verified that T285 = P165 = H143 = 40755.
# Find the next triangle number that is also pentagonal and hexagonal.
#
# Ans: 1533776805

def triangular(n):
    return n*(n+1)/2


def pentagonal(n):
    return n*(3*n-1)/2


def hexagonal(n):
    return n*(2*n-1)


nt = 286
np = 166
nh = 144


tria = triangular(nt)
penta = pentagonal(np)
hexa = hexagonal(nh)


while True:
    if tria < penta:
        nt += 1
        tria = triangular(nt)
    elif penta < tria:
        np += 1
        penta= pentagonal(np)
    else:
        while hexa < tria:
            nh += 1
            hexa = hexagonal(nh)
        if hexa == tria:
            print nt, np, nh, tria
            break
        nt += 1
        tria = triangular(nt)
        np += 1
        penta= pentagonal(np)
